##
# ZikulaSeaBreezeTheme config
##
admin:
  page: "admin.html.twig"
  block:
    positions:
      topnav: "Block/topnavblock.html.twig"
      search: "Block/searchblock.html.twig"
home:
  page: "home.html.twig"
  block:
    positions:
      left: "Block/lsblock.html.twig"
      right: "Block/rsblock.html.twig"
      center: "Block/ccblock.html.twig"
      topnav: "Block/topnavblock.html.twig"
      search: "Block/searchblock.html.twig"
master:
  page: "master.html.twig"
  block:
    positions:
      left: "Block/lsblock.html.twig"
      right: "Block/rsblock.html.twig"
      topnav: "Block/topnavblock.html.twig"
      search: "Block/searchblock.html.twig"
dizkus:
  pattern: ZikulaDizkusModule
  page: "norightcolumn.html.twig"
  block:
    positions:
      left: "Block/lsblock.html.twig"